name: Grammar Check for LaTeX

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  grammar-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install LanguageTool
      run: |
        wget -q https://languagetool.org/download/LanguageTool-stable.zip
        unzip -q LanguageTool-stable.zip -d languagetool

    - name: Run Grammar Check with LanguageTool
      run: |
        find . -name "*.tex" -exec languagetool/languagetool-commandline.jar \
        --language it --disableCategories LT-tex {} \;

    - name: Annotate Grammar Errors
      if: failure()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          ⚠️ Il controllo grammaticale con LanguageTool ha trovato problemi. Correggi gli errori e riprova.
          Puoi eseguire localmente `java -jar languagetool/languagetool-commandline.jar --language it <file.tex>` per dettagli.
