name: Grammar Check for LaTeX

on:
  push:
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Textidote and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install textidote

    - name: Grammar and Spell Check for LaTeX Files
      run: |
        # Process all .tex files and run Textidote for Italian
        for file in $(find . -name "*.tex"); do
          echo "Processing $file..."

          # Run Textidote with Italian as the language
          textidote check --language=it --latex $file || textidote check --language=en --latex $file
          
        done
