name: Grammar Check for LaTeX

on:
  push:
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Aspell and Dictionaries
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-it aspell-en

    - name: Spell Check for LaTeX Files
      run: |
        # File personalizzati per italiano e inglese
        PERSONAL_WORDLIST_IT="./.github/workflows/Dizionari_Latex/personal_wordlist_it.txt"
        PERSONAL_WORDLIST_EN="./.github/workflows/Dizionari_Latex/personal_wordlist_en.txt"

        # Verifica che i file di parole personalizzate esistano
        for wordlist in "$PERSONAL_WORDLIST_IT" "$PERSONAL_WORDLIST_EN"; do
          if [ ! -f "$wordlist" ]; then
            echo "File di parole personalizzate non trovato: $wordlist"
            exit 1
          fi
        done

        # Crea file temporanei per le parole non riconosciute
        TMP_FILE_IT=$(mktemp)
        TMP_FILE_EN=$(mktemp)
        FINAL_TMP_FILE=$(mktemp)

        # Processa tutti i file .tex
        for file in $(find . -name "*.tex"); do
          echo "Processing $file..."

          # Controllo ortografico in italiano
          aspell --mode=tex --lang=it --personal=$PERSONAL_WORDLIST_IT list < "$file" >> "$TMP_FILE_IT"
        done

        # Controlla se le parole italiane sono riconosciute in inglese
        if [ -s "$TMP_FILE_IT" ]; then
          echo "Parole non riconosciute in italiano trovate. Verifico in inglese..."
          while IFS= read -r word; do
            echo "$word" | aspell --lang=en --personal=$PERSONAL_WORDLIST_EN list >> "$TMP_FILE_EN"
          done < <(sort -u "$TMP_FILE_IT")
        fi

        # Combina le parole non riconosciute finali
        if [ -s "$TMP_FILE_EN" ]; then
          echo "Parole non riconosciute in nessuna lingua trovate:"
          sort -u "$TMP_FILE_EN" > "$FINAL_TMP_FILE"
          cat "$FINAL_TMP_FILE"
          exit 1
        else
          echo "Nessuna parola non riconosciuta trovata in entrambe le lingue."
        fi
