name: Grammar Check for LaTeX

on:
  push:
    paths:
      - 'Texstuff/**/*.tex'
  pull_request:
    paths:
      - 'Texstuff/**/*.tex'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Aspell and Dictionaries
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-it aspell-en

    - name: Spell Check for LaTeX Files
      run: |
        # Create a temporary file for unrecognized words
        TMP_FILE=$(mktemp)

        # Process all .tex files in the specified folder
        for file in $(find Texstuff -name "*.tex"); do
          echo "Processing $file..."

          # Remove LaTeX commands before running spell check
          sed 's/\\[a-zA-Z]*//g' "$file" | \
          aspell --lang=it list >> $TMP_FILE
        done

        echo "Checking unrecognized words in English..."
        # Check the unrecognized words against the English dictionary
        if [ -s "$TMP_FILE" ]; then
          echo "Unrecognized words found:"
          sort -u "$TMP_FILE" | tee unrecognized_words.txt
          # Run English spell check
          sort -u "$TMP_FILE" | aspell --lang=en list | tee errors_in_english.txt
        fi

    - name: Create Comment on Pull Request
      if: ${{ github.event_name == 'pull_request' && (steps.spell-check.outputs.errors || steps.spell-check.outputs.errors_in_english) }}
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const unrecognizedWordsPath = 'unrecognized_words.txt';
          const errorsInEnglishPath = 'errors_in_english.txt';
          
          let commentBody = '';

          if (fs.existsSync(unrecognizedWordsPath)) {
            const unrecognizedWords = fs.readFileSync(unrecognizedWordsPath, 'utf8');
            commentBody += '### Errors in Italian/Unrecognized words:\n```\n' + unrecognizedWords + '\n```\n';
          }

          if (fs.existsSync(errorsInEnglishPath)) {
            const errorsInEnglish = fs.readFileSync(errorsInEnglishPath, 'utf8');
            commentBody += '### Errors in English:\n```\n' + errorsInEnglish + '\n```\n';
          }

          if (commentBody) {
            commentBody = '## Grammar Check Results\n' + commentBody;
            await github.rest.issues.createComment({
              ...context.issue,
              body: commentBody
            });
          }
