name: Italian Grammar and Spell Check for LaTeX

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y hunspell hunspell-it texlive-full pandoc

    - name: Preprocess LaTeX Files
      run: |
        mkdir -p processed
        find . -name "*.tex" -exec sh -c \
        'pandoc -f latex -t plain "{}" -o "processed/$(basename "{}" .tex).txt"' \;

    - name: Run Spell Check
      run: |
        mkdir -p reports
        for file in processed/*.txt; do
          hunspell -d it_IT "$file" > "reports/$(basename "$file" .txt).report" || true
        done

    - name: Display Errors
      run: |
        echo "Spell Check Reports:"
        cat reports/*.report

    - name: Annotate Grammar Errors
      if: failure()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          ⚠️ Il controllo grammaticale/spell check ha trovato problemi nei file LaTeX:
          Controlla i dettagli nei log.
          Per eseguire localmente:
          1. Usa `pandoc` per estrarre testo dai file `.tex`.
          2. Controlla gli errori con `hunspell -d it_IT <file.txt>`.
