name: Grammar Check for LaTeX

on:
  push:
    paths:
      - 'Texstuff/**/*.tex'
  pull_request:
    paths:
      - 'Texstuff/**/*.tex'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Aspell and Dictionaries
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-it aspell-en

    - name: Spell Check for LaTeX Files
      id: spell-check
      run: |
        # Create temporary files for storing errors
        TMP_FILE=$(mktemp)
        UNRECOGNIZED_WORDS_FILE="unrecognized_words.txt"
        ERRORS_IN_ENGLISH_FILE="errors_in_english.txt"
        
        # Initialize files
        > $UNRECOGNIZED_WORDS_FILE
        > $ERRORS_IN_ENGLISH_FILE

        # Process all .tex files in the specified folder
        for file in $(find Texstuff -name "*.tex"); do
          echo "Processing $file..."

          # Remove LaTeX commands before running spell check
          sed 's/\\[a-zA-Z]*//g' "$file" | \
          aspell --lang=it list >> $TMP_FILE
        done

        # Save unrecognized words and check against the English dictionary
        if [ -s "$TMP_FILE" ]; then
          sort -u "$TMP_FILE" > $UNRECOGNIZED_WORDS_FILE
          sort -u "$TMP_FILE" | aspell --lang=en list > $ERRORS_IN_ENGLISH_FILE
        fi

        # Export results for later steps
        echo "UNRECOGNIZED_WORDS=$(cat $UNRECOGNIZED_WORDS_FILE | wc -l)" >> $GITHUB_ENV
        echo "ERRORS_IN_ENGLISH=$(cat $ERRORS_IN_ENGLISH_FILE | wc -l)" >> $GITHUB_ENV

    - name: Create Comment on Pull Request
      if: ${{ github.event_name == 'pull_request' && (env.UNRECOGNIZED_WORDS > 0 || env.ERRORS_IN_ENGLISH > 0) }}
      uses: actions/github-script@v6
      id: create-comment
      with:
        script: |
          const fs = require('fs');
          const unrecognizedWordsPath = 'unrecognized_words.txt';
          const errorsInEnglishPath = 'errors_in_english.txt';
          
          let commentBody = '## Grammar Check Results\n';

          if (fs.existsSync(unrecognizedWordsPath) && fs.readFileSync(unrecognizedWordsPath, 'utf8').trim()) {
            commentBody += '### Errors in Italian/Unrecognized words:\n```\n' + fs.readFileSync(unrecognizedWordsPath, 'utf8') + '\n```\n';
          }

          if (fs.existsSync(errorsInEnglishPath) && fs.readFileSync(errorsInEnglishPath, 'utf8').trim()) {
            commentBody += '### Errors in English:\n```\n' + fs.readFileSync(errorsInEnglishPath, 'utf8') + '\n```\n';
          }

          await github.rest.issues.createComment({
            ...context.issue,
            body: commentBody
          });

          // Pass a flag to indicate a comment was created
          core.setOutput('commented', true);

    - name: Fail if Errors Were Found
      if: ${{ steps.spell-check.outputs.UNRECOGNIZED_WORDS > 0 || steps.spell-check.outputs.ERRORS_IN_ENGLISH > 0 }}
      run: |
        echo "Errors found, pull request will be rejected."
        exit 1
