name: Grammar Check for LaTeX

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  grammar-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install TeXtidote
      run: |
        wget -q https://github.com/sylvainhalle/textidote/releases/latest/download/textidote.jar -O textidote.jar

    - name: Run Grammar Check
      run: |
        find . -name "*.tex" -exec java -jar textidote.jar --check it --check-only --no-pdflatex --ignore latex {} \;

    - name: Annotate Grammar Errors
      if: failure()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          ⚠️ Il controllo grammaticale ha trovato problemi. Correggi gli errori e riprova.
          Puoi eseguire localmente `java -jar textidote.jar --check it --no-pdflatex --ignore latex <file.tex>` per dettagli.
