name: Grammar Check for LaTeX

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tex'

jobs:
  grammar-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install TeXtidote
      run: |
        wget -q https://github.com/sylvainhalle/textidote/releases/latest/download/textidote.jar -O textidote.jar

    - name: Run Grammar Check
      run: |
        find . -name "*.tex" -exec java -jar textidote.jar --check it --quiet {} \;
