name: Grammar Check for LaTeX

on:
  pull_request:
    paths:
      - 'Texstuff/**/*.tex'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Aspell and Dictionaries
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-it aspell-en

    - name: Spell Check for LaTeX Files
      id: spell-check
      run: |
        # Create a temporary file for unrecognized words
        TMP_FILE=$(mktemp)
        ERRORS=""

        # Process all .tex files in the specified folder
        for file in $(find Texstuff -name "*.tex"); do
          echo "Processing $file..."
          
          # Remove LaTeX commands and perform Italian spell check
          UNRECOGNIZED=$(sed 's/\\[a-zA-Z]*//g' "$file" | aspell --lang=it list | sort -u)

          # Collect errors
          if [ -n "$UNRECOGNIZED" ]; then
            ERRORS="$ERRORS\n### Errors in $file (Italian):\n\`\`\`\n$UNRECOGNIZED\n\`\`\`"
          fi
        done

        # Check words unrecognized in Italian against the English dictionary
        if [ -n "$ERRORS" ]; then
          echo -e "$ERRORS"
          echo "::set-output name=errors::$ERRORS"
        fi
      continue-on-error: true

    - name: Comment on Pull Request
      if: steps.spell-check.outputs.errors != ''
      uses: actions/github-script@v6
      with:
        script: |
          const errors = process.env.ERRORS;
          const { context } = github;
          github.rest.issues.createComment({
            ...context.repo,
            issue_number: context.issue.number,
            body: `### Grammar Check Results\n${errors}\nPlease fix the errors above before merging.`
          })
