name: Grammar Check for LaTeX

on:
  push:
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Aspell and Dictionaries
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-it aspell-en

    - name: Spell Check for LaTeX Files
      run: |
        # File personalizzati per italiano e inglese
        PERSONAL_WORDLIST_IT="./Texstuff/personal_wordlist_it.txt"
        PERSONAL_WORDLIST_EN="./Texstuff/personal_wordlist_en.txt"

        # Verifica che i file di parole personalizzate esistano
        for wordlist in "$PERSONAL_WORDLIST_IT" "$PERSONAL_WORDLIST_EN"; do
          if [ ! -f "$wordlist" ]; then
            echo "File di parole personalizzate non trovato: $wordlist"
            exit 1
          fi
        done

        # Crea file temporaneo per le parole non riconosciute
        TMP_FILE_IT=$(mktemp)
        TMP_FILE_EN=$(mktemp)

        # Processa tutti i file .tex
        for file in $(find Texstuff -name "*.tex"); do
          echo "Processing $file..."

          # Rimuovi comandi LaTeX prima di controllare l'ortografia
          sed -E '
            s/\\[a-zA-Z@]+(\[[^]]*\])?(\{[^}]*\})?//g;
            s/\$[^\$]*\$//g;
            s/\$\$[^\$]*\$\$//g;
            s/%.*//g;
            s/[{}]//g;
          ' "$file" | \
          aspell --lang=it --personal=$PERSONAL_WORDLIST_IT list >> $TMP_FILE_IT

          # Controlla l'ortografia in inglese per le stesse parole
          cat "$TMP_FILE_IT" | aspell --lang=en --personal=$PERSONAL_WORDLIST_EN list >> $TMP_FILE_EN
        done

        # Controlla le parole non riconosciute in italiano
        if [ -s "$TMP_FILE_IT" ]; then
          echo "Unrecognized words in Italian:"
          sort -u "$TMP_FILE_IT" | tee unrecognized_words_it.txt

          if [ -s unrecognized_words_it.txt ]; then
            exit 1
          fi
        else
          echo "No unrecognized words found in Italian."
        fi

        # Controlla le parole non riconosciute in inglese
        if [ -s "$TMP_FILE_EN" ]; then
          echo "Unrecognized words in English:"
          sort -u "$TMP_FILE_EN" | tee unrecognized_words_en.txt

          if [ -s unrecognized_words_en.txt ]; then
            exit 1
          fi
        else
          echo "No unrecognized words found in English."
        fi
