name: Grammar Check for LaTeX

on:
  push:
    branches:
      - feature/*
  pull_request:

jobs:
  grammar-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install TeXtidote
      run: |
        wget -q https://github.com/sylvainhalle/textidote/releases/latest/download/textidote.jar -O textidote.jar

    - name: Run Grammar Check
      run: |
        find . -name "*.tex" -exec java -jar textidote.jar --check en --quiet {} \;
      continue-on-error: true

    - name: Annotate Grammar Errors
      if: failure()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          Grammar check found issues. Please review the report.
          Run `java -jar textidote.jar --check en --quiet <your-file.tex>` locally for more details.
