name: TeXtidote Action
uses: ChiefGokhlayeh/textidote-action@v5.3.1
with:
    # The root LaTeX file to be linted.
    root_file: 
    # Working directory to execute TeXtidote in.
    working_directory: # optional
    # The type of TeXtidote report to generate (referring to TeXtidote's --output option).
    report_type: # optional, default is html
    # The file path of TeXtidote report.
    report_file: # optional, default is report.html
    # The threshold for the number of warnings from TeXtidote above which the build is marked unstable.
    threshold_error: # optional
    # Extra arguments to be passed to TeXtidote.
    args: # optional
          