name: Grammar Check for LaTeX

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - '**/*.tex'
  pull_request:
    paths:
      - '**/*.tex'

jobs:
  grammar-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install LanguageTool
      run: |
        wget -q https://languagetool.org/download/LanguageTool-stable.zip
        unzip -q LanguageTool-stable.zip -d languagetool

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Preprocess LaTeX Files
      run: |
        mkdir -p processed
        find . -name "*.tex" -exec sh -c \
        'pandoc -f latex -t plain "{}" -o "processed/$(basename "{}" .tex).txt"' \;

    - name: Run Grammar Check with LanguageTool
      run: |
        for file in processed/*.txt; do
          java -jar languagetool/languagetool-commandline.jar \
          --language it "$file" || true
        done

    - name: Annotate Grammar Errors
      if: failure()
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          ⚠️ Il controllo grammaticale con LanguageTool ha trovato problemi. Correggi gli errori e riprova.
          Puoi eseguire localmente `pandoc -f latex -t plain <file.tex> | java -jar languagetool/languagetool-commandline.jar --language it` per dettagli.
