name: Grammar Check for LaTeX

on:
  push:
    paths:
      - 'Texstuff/**/*.tex'
  pull_request:
    paths:
      - 'Texstuff/**/*.tex'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Aspell and Dictionaries
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-it aspell-en

    - name: Spell Check for LaTeX Files
      run: |
        # Create a temporary file for unrecognized words
        TMP_FILE=$(mktemp)

        # Process all .tex files in the specified folder
        for file in $(find Texstuff -name "*.tex"); do
          echo "Processing $file..."

          # Remove LaTeX commands before running spell check
          sed 's/\\[a-zA-Z]*//g' "$file" | \
          aspell --lang=it list >> $TMP_FILE
        done

        echo "Checking unrecognized words in English..."
        # Check the unrecognized words against the English dictionary
        if [ -s "$TMP_FILE" ]; then
          echo "Unrecognized words found:"
          sort -u "$TMP_FILE" | tee unrecognized_words.txt
          # Run English spell check
          sort -u "$TMP_FILE" | aspell --lang=en list | tee errors_in_english.txt

          # If there are any errors, fail the job
          if [ -s errors_in_english.txt ]; then
            echo "Errors found in English or Italian. Failing job."
            cat errors_in_english.txt
            exit 1
          fi
        else
          echo "No unrecognized words found."
        fi