name: Spellcheck LaTeX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Python and dependencies
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install PySpelling
        run: |
          python -m pip install --upgrade pip
          pip install pyspelling

      # Run PySpelling with the configuration
      - name: Run Spellcheck
        run: |
          pyspelling -c spellcheck.yml
