name: Grammar Check for LaTeX

on:
  push:
    paths:
      - 'Texstuff/**/*.tex'
  pull_request:
    paths:
      - 'Texstuff/**/*.tex'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Aspell and Dictionaries
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-it aspell-en

    - name: Spell Check for LaTeX Files
      id: spellcheck
      run: |
        # Create a temporary file for unrecognized words
        TMP_FILE=$(mktemp)

        # Process all .tex files in the specified folder
        for file in $(find Texstuff -name "*.tex"); do
          echo "Processing $file..."

          # Remove LaTeX commands before running spell check
          sed 's/\\[a-zA-Z]*//g' "$file" | \
          aspell --lang=it list >> $TMP_FILE
        done

        echo "Checking unrecognized words in English..."
        # Check the unrecognized words against the English dictionary
        if [ -s "$TMP_FILE" ]; then
          echo "Unrecognized words found:"
          sort -u "$TMP_FILE" | tee unrecognized_words.txt
          # Run English spell check
          sort -u "$TMP_FILE" | aspell --lang=en list | tee errors_in_english.txt
        else
          echo "No unrecognized words found."
        fi

    - name: Create Comment on Pull Request
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        # Check if errors exist and create a comment
        if [[ -s unrecognized_words.txt || -s errors_in_english.txt ]]; then
          echo "Errors found, creating a comment on the PR."

          # Create the comment body with the errors found
          commentBody="## Grammar Check Results\n"

          if [ -s unrecognized_words.txt ]; then
            commentBody+="### Errors in Italian/Unrecognized words:\n\`\`\`\n$(cat unrecognized_words.txt)\n\`\`\`\n"
          fi

          if [ -s errors_in_english.txt ]; then
            commentBody+="### Errors in English:\n\`\`\`\n$(cat errors_in_english.txt)\n\`\`\`\n"
          fi

          # Post the comment using the GitHub API and token
          curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -d "{\"body\":\"$commentBody\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
        fi

    - name: Fail Pull Request if Errors Found
      if: ${{ github.event_name == 'pull_request' && (steps.spellcheck.outputs.unrecognized_words > 0 || steps.spellcheck.outputs.errors_in_english > 0) }}
      run: |
        echo "Found errors in the pull request. Failing job."
        exit 1
